"""Add data column to media

Revision ID: 2674e8fa0cda
Revises: 743999d9824e
Create Date: 2024-07-29 17:30:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2674e8fa0cda"
down_revision = "743999d9824e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("data", sa.LargeBinary(), nullable=False))
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(length=128),  # Correct the existing type
        type_=sa.String(length=256),  # Update to the new type
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=128),  # Revert to the original type
        existing_nullable=False,
    )
    op.drop_column("media", "data")
    # ### end Alembic commands ###
