# migrations/versions/58e557873f1a_add_user_pic.py
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58e557873f1a"
down_revision = "660dda240ed6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key("fk_comment_user", "user", ["user_id"], ["id"])

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key("fk_post_user", "user", ["user_id"], ["id"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_user_username_email")
        batch_op.create_index("ix_username_email", ["username", "email"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_username_email")
        batch_op.create_index(
            "ix_user_username_email", ["username", "email"], unique=False
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint("fk_post_user", type_="foreignkey")
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_constraint("fk_comment_user", type_="foreignkey")
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
