"""Remove redundant author foreign key from Post model

Revision ID: 64e2309e5b52
Revises: 61ed96014b95
Create Date: 2024-07-11 15:53:17.060864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e2309e5b52'
down_revision = '61ed96014b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_author_user', type_='foreignkey')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_post_author_user', 'user', ['author'], ['id'])

    # ### end Alembic commands ###
