"""Add post_id to media table

Revision ID: 6bbafb875f35
Revises: c557b4deb912
Create Date: 2024-07-29 14:03:56.539691

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6bbafb875f35"
down_revision = "c557b4deb912"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("post_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "media", "post", ["post_id"], ["id"])
    # Commented out to prevent errors due to existing data length
    # op.alter_column('user', 'password',
    #            existing_type=sa.VARCHAR(length=256),
    #            type_=sa.String(length=128),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out to match the upgrade script
    # op.alter_column('user', 'password',
    #            existing_type=sa.String(length=128),
    #            type_=sa.VARCHAR(length=256),
    #            existing_nullable=False)
    op.drop_constraint(None, "media", type_="foreignkey")
    op.drop_column("media", "post_id")
    # ### end Alembic commands ###
