"""Add media relationship to Post

Revision ID: 743999d9824e
Revises: 050dff5a6573
Create Date: 2024-07-29 15:30:24.743353

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "743999d9824e"
down_revision = "050dff5a6573"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_post_tag", "post_tags", type_="unique")
    op.drop_constraint("post_tags_tag_id_fkey", "post_tags", type_="foreignkey")
    op.drop_constraint("post_tags_post_id_fkey", "post_tags", type_="foreignkey")
    op.create_foreign_key(None, "post_tags", "post", ["post_id"], ["id"])
    op.create_foreign_key(None, "post_tags", "tag", ["tag_id"], ["id"])
    # Remove the following line
    # op.alter_column('user', 'password',
    #            existing_type=sa.VARCHAR(length=256),
    #            type_=sa.String(length=128),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user', 'password',
    #            existing_type=sa.String(length=128),
    #            type_=sa.VARCHAR(length=256),
    #            existing_nullable=False)
    op.drop_constraint(None, "post_tags", type_="foreignkey")
    op.drop_constraint(None, "post_tags", type_="foreignkey")
    op.create_foreign_key(
        "post_tags_post_id_fkey",
        "post_tags",
        "post",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "post_tags_tag_id_fkey",
        "post_tags",
        "tag",
        ["tag_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("unique_post_tag", "post_tags", ["post_id", "tag_id"])
    # ### end Alembic commands ###
