"""Add role to User model

Revision ID: a599f878035d
Revises: 047e09ccca2c
Create Date: 2024-06-26 17:38:12.921255

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a599f878035d"
down_revision = "047e09ccca2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role", sa.String(length=50), nullable=False, server_default="user"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###
