"""Added user Profile customization

Revision ID: afd83c764b9b
Revises: 3a9a8857f836
Create Date: 2024-07-04 12:08:21.925291

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "afd83c764b9b"
down_revision = "3a9a8857f836"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "author",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        batch_op.create_foreign_key("fk_post_author_user", "user", ["author"], ["id"])
        batch_op.drop_column("thumbnail_filename")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar", sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column("bio", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("social_media", sa.String(length=500), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("social_media")
        batch_op.drop_column("bio")
        batch_op.drop_column("avatar")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("thumbnail_filename", sa.VARCHAR(length=100), nullable=True)
        )
        batch_op.drop_constraint("fk_post_author_user", type_="foreignkey")
        batch_op.alter_column(
            "author",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
