"""empty message

Revision ID: c557b4deb912
Revises: b4137fcba888
Create Date: 2024-07-16 14:41:07.611882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c557b4deb912'
down_revision = 'b4137fcba888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_tags_post_id', type_='foreignkey')
        batch_op.drop_constraint('fk_post_tags_tag_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_post_tags_tag_id', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_post_tags_post_id', 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
