"""Add media filename to Post model

Revision ID: db0aea4adf9b
Revises: e871bcc4cdd3
Create Date: 2024-06-27 12:07:05.943410

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db0aea4adf9b"
down_revision = "e871bcc4cdd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("media_filename", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("media_filename")

    # ### end Alembic commands ###
